
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/fdfs?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 111111
  redis:
    host: localhost
    port: 6379
    password:
    database: 2
logging:
  level:
    root: info
    cn.uestc: info


mybatis:
  #mapper配置文件
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: cn.uestc.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
